### ISSUE TITLE
ASCII art in load scripts requires interactive shell.

### ISSUE THREAD

**Issue by VeryAngrySquirrel** [xobiomesh/ComfyUI_xObiomesh#1]
display_ascii_art() requires interaction, meaning that automatic restarts and other non-interactive shell sessions halt load until the user interacts.    This prevents me from using these nodes in a session that launches automatically on load.

**Comment by xobiomesh** [comment]
hey, sorry for the inconvenience, didn't expect to have someone actually pulling the repo this soon, but you're right user input should be removed... should run another shell and let this one do it's thing.. I'll fix  this asap. Thanks for the heads up!
